# Generated by Django 3.2.8 on 2021-10-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='comment',
            field=models.TextField(null=True, verbose_name='Transaction comments'),
        ),
    ]
